openapi: 3.0.1
info:
  title: local-dev
  description: ''
  version: 1.0.0
tags: []
paths:
  /flow:
    get:
      summary: 获取 flow 列表
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FlowListObject'
      security:
        - bearer: []
    post:
      summary: 创建 flow
      deprecated: false
      description: ''
      tags: []
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              properties:
                title:
                  type: string
                nodes:
                  type: string
                  nullable: true
                edges:
                  type: string
                  nullable: true
              required:
                - title
              type: object
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - bearer: []
  /flow/{id}:
    put:
      summary: 更新 flow
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              properties:
                nodes:
                  type: string
                  nullable: true
                edges:
                  type: string
                  nullable: true
                title:
                  type: string
                id:
                  type: integer
              required:
                - title
                - id
              type: object
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - bearer: []
    delete:
      summary: 删除 flow
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 删除成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - bearer: []
    get:
      summary: 获取 flow
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                title:
                  type: string
                nodes:
                  type: string
                  nullable: true
                edges:
                  type: string
                  nullable: true
                created_at:
                  type: string
              required:
                - title
                - id
                - created_at
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                properties: {}
      security:
        - bearer: []
components:
  schemas:
    FlowListObject:
      properties:
        title:
          type: string
        created_at:
          type: string
        id:
          type: integer
      type: object
      required:
        - title
        - created_at
        - id
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
servers: []
