/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Flow Editor
 * Flow Editor APIs
 * OpenAPI spec version: 1.0
 */
import * as axios from "axios"
import type { AxiosRequestConfig, AxiosResponse } from "axios"
export interface FlowUpdateFlowInput {
  edges?: string
  id?: number
  nodes?: string
  owner?: string
  title?: string
}

export interface FlowFlowListObjectOutput {
  createdAt?: string
  id?: number
  title?: string
}

export interface FlowFlowDetailOutput {
  createdAt?: string
  edges?: string
  id?: number
  nodes?: string
  title?: string
}

export interface FlowCreateFlowInput {
  edges?: string
  nodes?: string
  owner?: string
  title?: string
}

export interface AccountAccountOutput {
  activated?: boolean
  membership?: number
}

/**
 * @summary get account
 */
export const getAccount = <TData = AxiosResponse<AccountAccountOutput>>(
  options?: AxiosRequestConfig,
): Promise<TData> => {
  return axios.default.get(`/account`, options)
}

export type GetAccountResult = AxiosResponse<AccountAccountOutput>
