/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * Flow Editor
 * Flow Editor APIs
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "../lib/http/instance"
export interface FlowUpdateFlowInput {
  edges?: string
  id: number
  nodes?: string
  owner?: string
  title: string
}

export interface FlowFlowListObjectOutput {
  created_at: string
  id: number
  title: string
}

export interface FlowFlowDetailOutput {
  created_at: string
  edges?: string
  id: number
  nodes?: string
  title: string
}

export interface FlowCreateFlowInput {
  edges?: string
  nodes?: string
  owner?: string
  title: string
}

export interface AccountAccountOutput {
  activated: boolean
  membership: number
}

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * @summary get account
 */
export const getAccount = (options?: SecondParameter<typeof customInstance>) => {
  return customInstance<AccountAccountOutput>({ url: `/account`, method: "GET" }, options)
}

export type GetAccountResult = NonNullable<Awaited<ReturnType<typeof getAccount>>>
