/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * 流程编辑器 API
 * OpenAPI spec version: 0.0.1
 */
import type { AccountInfo } from "./model"
import { customInstance } from "../lib/http/instance"

type SecondParameter<T extends (...args: any) => any> = Parameters<T>[1]

/**
 * Get account
 * @summary getAccount account
 */
export const getAccount = (options?: SecondParameter<typeof customInstance>) => {
  return customInstance<AccountInfo>({ url: `/account`, method: "GET" }, options)
}

export type GetAccountResult = NonNullable<Awaited<ReturnType<typeof getAccount>>>
