/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * 流程编辑器 API
 * OpenAPI spec version: 0.0.1
 */

export interface AccountInfo {
  activated: boolean
  membership: number
  roles: string[]
  user_id: string
}
