/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * 流程编辑器 API
 * OpenAPI spec version: 0.0.1
 */

export interface CreateFlowRequestBody {
  /** flow 边 */
  edges?: string
  /** flow 节点 */
  nodes?: string
  /** flow 标题 */
  title?: string
}
