/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 流程编辑器 API
 * OpenAPI spec version: 0.0.1
 */

export interface FlowDetailData {
  /** flow 创建时间 */
  created_at: string
  /** flow 数据 */
  data?: string
  /** flow id */
  id: number
  /** flow 标题 */
  title: string
}
