/**
 * Generated by orval v6.29.1 🍺
 * Do not edit manually.
 * 流程编辑器 API
 * OpenAPI spec version: 0.0.1
 */

export interface FlowDetailData {
  /** flow 创建时间 */
  created_at: string
  /** flow 边 */
  edges?: string
  /** flow id */
  id: number
  /** flow 节点 */
  nodes?: string
  /** flow 标题 */
  title: string
}
