/**
 * Generated by orval v6.30.2 🍺
 * Do not edit manually.
 * 流程编辑器 API
 * OpenAPI spec version: 0.0.1
 */

export interface UpdateFlowData {
  /** flow 数据 */
  data?: string
  /** flow 标题 */
  title?: string
}
